import { useEffect, useState } from "react";
import { blackjackPayout, caseCatalog, dealerTurn, draw, handValue, mineMultiplier, openCase, randomFloat, shuffledDeck } from "./gameLogic";

const API_URL = import.meta.env.VITE_API_URL?.replace(/\/$/, "") || (import.meta.env.PROD ? window.location.origin : "");
const STARTER_BALANCE = 10000;
const NAV = [["PLAY", [["⌂", "Home"], ["♠", "Blackjack"], ["◌", "Mines"], ["◈", "Dice"], ["◐", "Coinflip"], ["🎁", "Cases"], ["◎", "Jackpot"]]], ["COMMUNITY", [["♜", "Leaderboard"], ["◉", "Profile"], ["⚙", "Admin"]]]];
const liveBets = [["♠", "Blackjack", "NovaLuck", "2,500", "2.00×", "+2,500"], ["◌", "Mines", "petmaster", "750", "1.84×", "+630"], ["◈", "Dice", "StarBlox", "1,200", "0.00×", "—"], ["◐", "Coinflip", "GemRunner", "15,000", "1.98×", "+14,700"]];
const leaderboard = [["LunaPaws", "48,230"], ["NovaLuck", "41,900"], ["GemRunner", "36,660"], ["MintyGems", "32,510"], ["DiceWizard", "28,940"]];
const money = (value) => Number(value || 0).toLocaleString("en-US");
const bet = (value, balance) => Math.max(10, Math.min(Math.floor(Number(value) || 0), balance));

function GameShell({ title, description, children, right }) { return <><div className="page-heading"><div><p className="eyebrow">PETLUCK GAMES</p><h1>{title}</h1><p>{description}</p></div>{right}</div>{children}</>; }
function Card({ card, hidden = false }) { return <div className={`playing-card ${hidden ? "hidden-card" : ""}`}>{hidden ? "?" : <><b>{card.rank}</b><span>{card.suit}</span></>}</div>; }

export default function App() {
  const [page, setPage] = useState("Home"); const [sidebarOpen, setSidebarOpen] = useState(true); const [notice, setNotice] = useState(""); const [user, setUser] = useState(null);
  const [loginOpen, setLoginOpen] = useState(false); const [robloxUsername, setRobloxUsername] = useState(""); const [phrase, setPhrase] = useState(""); const [loginStep, setLoginStep] = useState("start"); const [busy, setBusy] = useState(false);
  const [balance, setBalance] = useState(() => Number(localStorage.getItem("petluck-practice-balance")) || STARTER_BALANCE);
  const [inventory, setInventory] = useState(() => JSON.parse(localStorage.getItem("petluck-practice-inventory") || "[]")); const [history, setHistory] = useState(() => JSON.parse(localStorage.getItem("petluck-practice-history") || "[]"));
  const [blackjack, setBlackjack] = useState(null); const [blackjackBet, setBlackjackBet] = useState(250); const [mines, setMines] = useState(null); const [minesBet, setMinesBet] = useState(250); const [mineCount, setMineCount] = useState(3);
  const [diceBet, setDiceBet] = useState(250); const [diceTarget, setDiceTarget] = useState(50); const [diceLast, setDiceLast] = useState(null); const [coinBet, setCoinBet] = useState(250); const [coinLast, setCoinLast] = useState(null); const [caseResult, setCaseResult] = useState(null); const [jackpotEntry, setJackpotEntry] = useState(500); const [jackpotEntered, setJackpotEntered] = useState(0);
  const [adminTab, setAdminTab] = useState("Overview"); const [adminConfig, setAdminConfig] = useState(() => JSON.parse(localStorage.getItem("petluck-admin-settings") || '{"blackjack":1,"dice":1,"mines":1,"cases":3}'));
  useEffect(() => { localStorage.setItem("petluck-practice-balance", String(balance)); }, [balance]); useEffect(() => { localStorage.setItem("petluck-practice-inventory", JSON.stringify(inventory)); }, [inventory]); useEffect(() => { localStorage.setItem("petluck-practice-history", JSON.stringify(history.slice(0, 24))); }, [history]); useEffect(() => { localStorage.setItem("petluck-admin-settings", JSON.stringify(adminConfig)); }, [adminConfig]);
  useEffect(() => { if (!API_URL) return; fetch(`${API_URL}/api/me`, { credentials: "include" }).then((response) => response.ok ? response.json() : null).then((data) => data?.user && setUser(data.user)).catch(() => {}); }, []);
  function notify(text) { setNotice(text); window.setTimeout(() => setNotice(""), 3400); } function record(game, amount, result, payout = 0) { setHistory((prior) => [{ game, amount, result, payout, at: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) }, ...prior]); }
  function canAfford(amount) { if (amount > balance) { notify("Your practice wallet does not have enough gems."); return false; } return true; } function spend(amount) { setBalance((prior) => prior - amount); } function add(amount) { setBalance((prior) => prior + amount); }
  function go(name) { setPage(name); if (window.innerWidth < 900) setSidebarOpen(false); }
  async function beginRoblox(event) { event.preventDefault(); if (!API_URL) return notify("Login becomes available after the private API is deployed."); setBusy(true); try { const response = await fetch(`${API_URL}/auth/roblox/start`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username: robloxUsername }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setRobloxUsername(data.username); setPhrase(data.phrase); setLoginStep("verify"); } catch (error) { notify(error.message || "Could not start verification."); } finally { setBusy(false); } }
  async function verifyRoblox() { setBusy(true); try { const response = await fetch(`${API_URL}/auth/roblox/verify`, { method: "POST", credentials: "include" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setUser(data.user); setLoginOpen(false); notify(`Welcome, @${data.user.robloxUsername}.`); } catch (error) { notify(error.message || "Verification failed."); } finally { setBusy(false); } }
  function startBlackjack() { const stake = bet(blackjackBet, balance); if (!canAfford(stake)) return; const deck = shuffledDeck(); const first = draw(deck); const second = draw(first.deck); const dealerOne = draw(second.deck); const dealerTwo = draw(dealerOne.deck); const round = { deck: dealerTwo.deck, dealer: [dealerOne.card, dealerTwo.card], hands: [{ cards: [first.card, second.card], bet: stake, split: false }], active: 0, settled: false, message: "Your turn" }; spend(stake); setBlackjack(round); if (handValue(round.hands[0].cards) === 21 || handValue(round.dealer) === 21) settleBlackjack(round); }
  function settleBlackjack(round) { const end = dealerTurn(round.deck, round.dealer); const outcomes = round.hands.map((hand) => blackjackPayout(hand, end.cards)); const payout = outcomes.reduce((sum, entry) => sum + entry.payout, 0); if (payout) add(payout); const result = outcomes.map((entry) => entry.result).join(" / "); record("Blackjack", round.hands.reduce((sum, hand) => sum + hand.bet, 0), result, payout); setBlackjack({ ...round, deck: end.deck, dealer: end.cards, settled: true, outcomes, message: `${result} · ${payout ? `paid ${money(payout)}` : "no payout"}` }); }
  function nextBlackjackHand(round, updatedHand) { const hands = round.hands.map((hand, index) => index === round.active ? updatedHand : hand); const active = round.active + 1; if (active >= hands.length) settleBlackjack({ ...round, hands }); else setBlackjack({ ...round, hands, active, message: `Hand ${active + 1} of ${hands.length}` }); }
  function blackjackHit() { if (!blackjack || blackjack.settled) return; const next = draw(blackjack.deck); const hand = { ...blackjack.hands[blackjack.active], cards: [...blackjack.hands[blackjack.active].cards, next.card] }; const round = { ...blackjack, deck: next.deck }; if (handValue(hand.cards) >= 21) nextBlackjackHand(round, hand); else setBlackjack({ ...round, hands: round.hands.map((item, index) => index === round.active ? hand : item) }); }
  function blackjackStand() { if (blackjack && !blackjack.settled) nextBlackjackHand(blackjack, blackjack.hands[blackjack.active]); }
  function blackjackDouble() { if (!blackjack || blackjack.settled) return; const hand = blackjack.hands[blackjack.active]; if (hand.cards.length !== 2 || !canAfford(hand.bet)) return notify("Double is available only on your first two cards."); spend(hand.bet); const next = draw(blackjack.deck); nextBlackjackHand({ ...blackjack, deck: next.deck }, { ...hand, bet: hand.bet * 2, cards: [...hand.cards, next.card] }); }
  function blackjackSplit() { if (!blackjack || blackjack.settled) return; const hand = blackjack.hands[blackjack.active]; if (hand.cards.length !== 2 || hand.cards[0].rank !== hand.cards[1].rank || !canAfford(hand.bet)) return notify("Split requires a matching pair and another equal bet."); spend(hand.bet); const one = draw(blackjack.deck); const two = draw(one.deck); const splitHands = [{ cards: [hand.cards[0], one.card], bet: hand.bet, split: true }, { cards: [hand.cards[1], two.card], bet: hand.bet, split: true }]; setBlackjack({ ...blackjack, deck: two.deck, hands: [...blackjack.hands.slice(0, blackjack.active), ...splitHands, ...blackjack.hands.slice(blackjack.active + 1)], message: "Split into two hands" }); }
  function startMines() { const stake = bet(minesBet, balance); if (!canAfford(stake)) return; const positions = new Set(); while (positions.size < mineCount) positions.add(Math.floor(randomFloat() * 25)); spend(stake); setMines({ bet: stake, positions, opened: [], active: true }); }
  function revealMine(index) { if (!mines?.active || mines.opened.includes(index)) return; if (mines.positions.has(index)) { record("Mines", mines.bet, "Mine", 0); setMines({ ...mines, opened: [...mines.opened, index], active: false, lost: true }); return; } setMines({ ...mines, opened: [...mines.opened, index] }); }
  function cashoutMines() { if (!mines?.active || mines.opened.length === 0) return; const multiplier = mineMultiplier(mines.opened.length, mineCount); const payout = Math.floor(mines.bet * multiplier); add(payout); record("Mines", mines.bet, `Cashed at ${multiplier}×`, payout); setMines({ ...mines, active: false, payout, multiplier }); }
  function rollDice() { const stake = bet(diceBet, balance); if (!canAfford(stake)) return; const roll = Math.floor(randomFloat() * 10000) / 100 + .01; const won = roll < diceTarget; const multiplier = Math.floor((.99 / (diceTarget / 100)) * 100) / 100; const payout = won ? Math.floor(stake * multiplier) : 0; spend(stake); if (payout) add(payout); setDiceLast({ roll, won, payout, multiplier }); record("Dice", stake, won ? "Win" : "Lose", payout); }
  function flipCoin(choice) { const stake = bet(coinBet, balance); if (!canAfford(stake)) return; const landed = randomFloat() < .5 ? "Heads" : "Tails"; const won = landed === choice; const payout = won ? Math.floor(stake * 1.98) : 0; spend(stake); if (payout) add(payout); setCoinLast({ choice, landed, won, payout }); record("Coinflip", stake, won ? "Win" : "Lose", payout); }
  function openPetCase(caseInfo) { if (!canAfford(caseInfo.cost)) return; const item = openCase(caseInfo); spend(caseInfo.cost); const entry = { ...item, case: caseInfo.name, id: `${Date.now()}-${item.name}` }; setInventory((prior) => [entry, ...prior]); setCaseResult(entry); record("Cases", caseInfo.cost, item.name, item.value); }
  function resetPractice() { setBalance(STARTER_BALANCE); setInventory([]); setHistory([]); setBlackjack(null); setMines(null); notify("Practice wallet and history reset."); }
  const selectedHand = blackjack?.hands[blackjack.active];
  function Home() { const tiles = [["♠", "Blackjack", "Cards, split & dealer rules", "violet"], ["◌", "Mines", "Find gems before a mine", "cyan"], ["◈", "Dice", "Choose your chance", "amber"], ["◐", "Coinflip", "Heads or tails, instant", "rose"], ["🎁", "Cases", "Weighted collectible drops", "lime"], ["◎", "Jackpot", "Community prize pool", "blue"]]; return <><section className="hero"><div><p className="eyebrow">PETLUCK • PRELAUNCH</p><h1>Play fair.<br /><em>Get lucky.</em></h1><p>PetLuck is becoming a standalone game platform. Try the complete game flow with practice gems while accounts and permanent storage are prepared.</p><div className="row"><button className="primary" onClick={() => go("Blackjack")}>Play blackjack <b>→</b></button><button className="secondary" onClick={() => go("Cases")}>Browse cases</button></div></div><div className="hero-mark"><span>◆</span><i>✦</i><i>✦</i><i>✦</i></div></section><section className="stat-grid"><Stat icon="◉" label="PRACTICE WALLET" value={money(balance)} text="Saved in this browser" /><Stat icon="◎" label="JACKPOT POOL" value="24,580" text="Standalone demo round" /><Stat icon="🎁" label="INVENTORY ITEMS" value={inventory.length} text="Items you opened" /></section><SectionTitle eyebrow="CHOOSE A GAME" title="Play your way" action="All games" onClick={() => go("Blackjack")} /><section className="game-grid">{tiles.map(([icon, title, text, tone]) => <button className={`game-tile ${tone}`} onClick={() => go(title)} key={title}><span className="tile-icon">{icon}</span><span className="arrow">↗</span><h3>{title}</h3><p>{text}</p></button>)}</section><LiveBets /></>; }
  function LiveBets() { return <section className="panel live-panel"><div className="panel-header"><div><p className="eyebrow">COMMUNITY ACTION</p><h2>Live bets <i>●</i></h2></div><button className="secondary small" onClick={() => go("Leaderboard")}>Leaderboard</button></div><div className="table">{liveBets.map(([icon, game, player, stake, mult, payout]) => <div className="table-row" key={player}><span className="table-icon">{icon}</span><b>{game}</b><span className="muted">◉ {player}</span><span>{stake}</span><span className="pill">{mult}</span><strong className={payout === "—" ? "muted" : "positive"}>{payout}</strong></div>)}</div></section>; }
  function Blackjack() { return <GameShell title="Blackjack" description="Dealer stands on 17. Blackjack pays 3:2. Split matching cards or double your first two cards." right={<div className="fair-pill">◆ Practice rules</div>}><section className="game-layout"><aside className="control-panel"><h3>Blackjack table</h3><BetInput value={blackjackBet} setValue={setBlackjackBet} balance={balance} /><div className="split-actions"><button disabled={!blackjack || blackjack.settled || selectedHand?.cards.length !== 2} onClick={blackjackHit}>Hit</button><button disabled={!blackjack || blackjack.settled} onClick={blackjackStand}>Stand</button><button disabled={!blackjack || blackjack.settled} onClick={blackjackDouble}>Double</button><button disabled={!blackjack || blackjack.settled} onClick={blackjackSplit}>Split</button></div><button className="primary full" onClick={startBlackjack}>{blackjack?.settled ? "New hand" : "Deal"} · {money(bet(blackjackBet, balance))}</button><p className="fine-print">A 52-card deck is shuffled for every hand. Practice balance is local to this browser.</p></aside><section className="blackjack-table"><div className="dealer-zone"><label>DEALER · {blackjack?.settled ? handValue(blackjack.dealer) : "?"}</label><div className="cards">{blackjack ? blackjack.dealer.map((card, index) => <Card key={index} card={card} hidden={!blackjack.settled && index === 1} />) : <EmptyCards count={2} />}</div></div><div className="table-status">{blackjack?.message || "Place a bet to deal"}</div><div className="player-zone">{blackjack ? blackjack.hands.map((hand, index) => <div className={`hand ${index === blackjack.active && !blackjack.settled ? "current" : ""}`} key={index}><label>YOU {blackjack.hands.length > 1 ? `· HAND ${index + 1}` : ""} · {handValue(hand.cards)}</label><div className="cards">{hand.cards.map((card, cardIndex) => <Card key={cardIndex} card={card} />)}</div>{blackjack.outcomes?.[index] && <b className={blackjack.outcomes[index].payout ? "positive" : "negative"}>{blackjack.outcomes[index].result}</b>}</div>) : <div className="hand"><label>YOU · —</label><EmptyCards count={2} /></div>}</div></section></section></GameShell>; }
  function Mines() { const multiplier = mines?.opened.length ? mineMultiplier(mines.opened.length, mineCount) : 1; return <GameShell title="Mines" description="Pick safe tiles and cash out whenever you choose. Every safe reveal increases the payout." right={<div className="fair-pill">{mineCount} mines · {mines?.opened.length || 0} safe</div>}><section className="mines-layout"><aside className="control-panel"><h3>Choose your risk</h3><BetInput value={minesBet} setValue={setMinesBet} balance={balance} /><label className="field-label">Mines<select value={mineCount} disabled={mines?.active} onChange={(event) => setMineCount(Number(event.target.value))}>{[1, 3, 5, 7, 10].map((value) => <option value={value} key={value}>{value} mines</option>)}</select></label><div className="payout-box"><span>Current payout</span><b>{mines?.opened.length ? `${multiplier}×` : "—"}</b><small>{mines?.opened.length ? `${money(Math.floor(mines.bet * multiplier))} gems` : "Reveal a safe tile"}</small></div>{mines?.active ? <button className="primary full" onClick={cashoutMines} disabled={!mines.opened.length}>Cash out {mines.opened.length ? money(Math.floor(mines.bet * multiplier)) : ""}</button> : <button className="primary full" onClick={startMines}>Start game · {money(bet(minesBet, balance))}</button>}<p className="fine-print">The multiplier is based on remaining safe-tile probability with a 1% practice house edge.</p></aside><section className="mine-board">{Array.from({ length: 25 }, (_, index) => { const opened = mines?.opened.includes(index); const mine = mines?.positions.has(index); return <button className={`mine-cell ${opened ? (mine ? "bomb" : "safe") : ""}`} onClick={() => revealMine(index)} disabled={!mines?.active || opened} key={index}>{opened ? (mine ? "✹" : "◆") : ""}</button>; })}</section></section></GameShell>; }
  function Dice() { const chance = diceTarget; const multiplier = Math.floor((.99 / (chance / 100)) * 100) / 100; return <GameShell title="Dice" description="Roll under your target. Lower targets have larger multipliers." right={<div className="fair-pill">Under {chance.toFixed(2)} · {multiplier}×</div>}><section className="single-game"><div className="dice-visual"><div className="dice-number">{diceLast ? diceLast.roll.toFixed(2) : "—"}</div><p>{diceLast ? (diceLast.won ? `Won ${money(diceLast.payout)} gems` : "Try another roll") : "Your last roll appears here"}</p><div className="dice-track"><i style={{ width: `${chance}%` }} /><b style={{ left: `${chance}%` }} /></div><div className="track-label"><span>0.00</span><span>Target {chance.toFixed(2)}</span><span>100.00</span></div></div><aside className="control-panel compact-control"><h3>Place a roll</h3><BetInput value={diceBet} setValue={setDiceBet} balance={balance} /><label className="field-label">Win chance<input type="range" min="5" max="95" value={diceTarget} onChange={(event) => setDiceTarget(Number(event.target.value))} /><b>{chance.toFixed(2)}%</b></label><div className="payout-box"><span>Multiplier</span><b>{multiplier}×</b><small>Win below {chance.toFixed(2)}</small></div><button className="primary full" onClick={rollDice}>Roll under {chance.toFixed(2)}</button></aside></section></GameShell>; }
  function Coinflip() { return <GameShell title="Coinflip" description="Pick a side. A correct call pays 1.98×, including your stake." right={<div className="fair-pill">49.5% return · 1.98×</div>}><section className="single-game"><div className={`coin-stage ${coinLast?.landed?.toLowerCase() || ""}`}><div className="coin"><span>{coinLast?.landed?.[0] || "?"}</span></div><h2>{coinLast ? `${coinLast.landed} landed` : "Choose your side"}</h2><p>{coinLast ? (coinLast.won ? `You won ${money(coinLast.payout)} gems.` : "The coin did not land your way.") : "A secure browser random value decides every practice flip."}</p></div><aside className="control-panel compact-control"><h3>Place a flip</h3><BetInput value={coinBet} setValue={setCoinBet} balance={balance} /><div className="choice-buttons"><button onClick={() => flipCoin("Heads")}>Heads</button><button onClick={() => flipCoin("Tails")}>Tails</button></div><p className="fine-print">Stake: {money(bet(coinBet, balance))} gems · payout: {money(Math.floor(bet(coinBet, balance) * 1.98))} gems</p></aside></section></GameShell>; }
  function Cases() { return <GameShell title="Cases" description="Open a case to add a randomized collectible to your browser inventory." right={<button className="secondary" onClick={() => go("Profile")}>View inventory ({inventory.length})</button>}><section className="case-grid">{caseCatalog.map((caseInfo) => <article className={`case-card ${caseInfo.accent}`} key={caseInfo.id}><div className="case-icon">🎁</div><p className="eyebrow">{caseInfo.drops.length} WEIGHTED DROPS</p><h2>{caseInfo.name}</h2><p>Possible values: {money(Math.min(...caseInfo.drops.map((item) => item.value)))}–{money(Math.max(...caseInfo.drops.map((item) => item.value)))}</p><button className="primary full" onClick={() => openPetCase(caseInfo)}>Open · {money(caseInfo.cost)}</button><details><summary>View odds</summary>{caseInfo.drops.map((drop) => <div className="drop-row" key={drop.name}><span>{drop.name}</span><b>{(drop.weight / 10).toFixed(1)}%</b><small>{money(drop.value)} gems</small></div>)}</details></article>)}</section>{caseResult && <section className="result-banner"><span>✦</span><div><p className="eyebrow">CASE OPENED</p><h2>{caseResult.name}</h2><p>Added to your inventory · reference value {money(caseResult.value)} gems</p></div><button className="secondary" onClick={() => setCaseResult(null)}>Dismiss</button></section>}</GameShell>; }
  function Jackpot() { const pool = 24580 + jackpotEntered; function join() { const stake = bet(jackpotEntry, balance); if (!canAfford(stake)) return; spend(stake); setJackpotEntered((prior) => prior + stake); record("Jackpot", stake, "Entered", 0); notify("Your practice entry is in the next demo round."); } return <GameShell title="Daily jackpot" description="A simple weighted pool: every gem entered becomes a ticket for the round." right={<div className="fair-pill">Next draw · 01:42</div>}><section className="jackpot-layout"><div className="jackpot-ring"><div><span>◆</span><b>{money(pool)}</b><small>GEM POOL</small><p>{jackpotEntered ? `${money(jackpotEntered)} of your entries` : "No entries yet"}</p></div></div><aside className="control-panel compact-control"><h3>Enter the pool</h3><BetInput value={jackpotEntry} setValue={setJackpotEntry} balance={balance} /><div className="payout-box"><span>Your chance</span><b>{jackpotEntered ? `${((jackpotEntered / pool) * 100).toFixed(2)}%` : "0.00%"}</b><small>Based on your current entries</small></div><button className="primary full" onClick={join}>Enter jackpot</button><p className="fine-print">This prelaunch version records only your local practice entries. The final draw will be server verified.</p></aside></section></GameShell>; }
  function Profile() { return <><div className="profile-hero"><div className="profile-avatar">{(user?.robloxUsername || "P")[0].toUpperCase()}</div><div><p className="eyebrow">YOUR PETLUCK PROFILE</p><h1>{user?.robloxUsername ? `@${user.robloxUsername}` : "Practice player"}</h1><p>{user?.robloxVerified ? "Roblox account verified" : "Guest mode · data stays in this browser"}</p></div><button className="secondary" onClick={() => { setLoginOpen(true); setLoginStep("start"); }}>{user ? "Verify another account" : "Verify Roblox"}</button></div><section className="stat-grid"><Stat icon="◆" label="AVAILABLE GEMS" value={money(balance)} text="Practice wallet" /><Stat icon="🎁" label="COLLECTIBLES" value={inventory.length} text="From opened cases" /><Stat icon="◎" label="ROUNDS LOGGED" value={history.length} text="Local play history" /></section><section className="profile-columns"><section className="panel"><div className="panel-header"><h2>Inventory</h2><span className="muted">{inventory.length} items</span></div>{inventory.length ? <div className="inventory-list">{inventory.map((item) => <div className="inventory-item" key={item.id}><span>✦</span><div><b>{item.name}</b><small>{item.case}</small></div><strong>{money(item.value)}</strong></div>)}</div> : <Empty text="Your opened case items appear here." />}</section><section className="panel"><div className="panel-header"><h2>Recent sessions</h2><button className="text-button" onClick={resetPractice}>Reset practice data</button></div>{history.length ? <History rows={history} /> : <Empty text="Your game outcomes appear here." />}</section></section></>; }
  function Leaderboard() { return <GameShell title="Wager leaderboard" description="A preview of the player-ranking experience for the standalone platform."><section className="podium"><article><span>2</span><i>◉</i><b>NovaLuck</b><small>41,900 gems</small></article><article className="first"><span>1</span><i>♛</i><b>LunaPaws</b><small>48,230 gems</small></article><article><span>3</span><i>◉</i><b>GemRunner</b><small>36,660 gems</small></article></section><section className="panel leaderboard-list">{leaderboard.map(([name, value], index) => <div key={name}><span>#{index + 1}</span><b>{name}</b><small>Wagered</small><strong>{value} gems</strong></div>)}</section></GameShell>; }
  function Admin() { const setEdge = (key, value) => setAdminConfig((prior) => ({ ...prior, [key]: Number(value) })); return <GameShell title="Admin center" description="Site-native settings for the standalone platform. These controls are currently local preview settings, not public live controls." right={<div className="admin-badge">⚙ LOCAL PREVIEW</div>}><div className="admin-tabs">{["Overview", "Games", "Wallet", "Transactions"].map((tab) => <button className={adminTab === tab ? "active" : ""} onClick={() => setAdminTab(tab)} key={tab}>{tab}</button>)}</div>{adminTab === "Overview" && <section className="admin-cards"><Stat icon="◉" label="PLAYER STORE" value="Browser local" text="Replace with a managed database before launch." /><Stat icon="◆" label="PRACTICE BALANCE" value={money(balance)} text="Current browser only." /><Stat icon="⚙" label="GAME MODULES" value="6 enabled" text="Blackjack, mines, dice, coinflip, cases, jackpot." /></section>}{adminTab === "Games" && <section className="panel settings-form"><h2>Game configuration</h2><p>Keep each edge explicit and server-enforced when production storage is connected.</p>{[["blackjack", "Blackjack house edge"], ["dice", "Dice house edge"], ["mines", "Mines house edge"], ["cases", "Case service fee"]].map(([key, label]) => <label key={key}>{label}<div><input type="number" min="0" max="25" value={adminConfig[key]} onChange={(event) => setEdge(key, event.target.value)} /><span>%</span></div></label>)}</section>}{adminTab === "Wallet" && <section className="panel settings-form"><h2>Practice wallet tools</h2><p>These actions affect this browser’s prelaunch data only.</p><div className="row"><button className="primary" onClick={() => { add(1000); notify("Added 1,000 practice gems."); }}>Add 1,000 gems</button><button className="danger" onClick={resetPractice}>Reset wallet & history</button></div></section>}{adminTab === "Transactions" && <section className="panel"><div className="panel-header"><h2>Local transaction log</h2><span className="muted">{history.length} entries</span></div>{history.length ? <History rows={history} /> : <Empty text="No local game transactions yet." />}</section>}</GameShell>; }
  const Page = ({ Home, Blackjack, Mines, Dice, Coinflip, Cases, Jackpot, Profile, Leaderboard, Admin })[page] || Home;
  return <div className={`app-shell ${sidebarOpen ? "sidebar-open" : "sidebar-closed"}`}><aside className="sidebar"><button className="brand" onClick={() => go("Home")}><span>✦</span><b>pet<span>luck</span></b></button><button className="sidebar-toggle" onClick={() => setSidebarOpen((open) => !open)} aria-label="Toggle menu">☰ <span>Menu</span></button>{NAV.map(([label, items]) => <div className="nav-group" key={label}><p>{label}</p>{items.map(([icon, name]) => <button className={page === name ? "selected" : ""} onClick={() => go(name)} key={name}><i>{icon}</i><span>{name}</span></button>)}</div>)}<div className="sidebar-bottom"><button onClick={() => setLoginOpen(true)}><i>◉</i><span>{user ? "Account" : "Verify Roblox"}</span></button><button onClick={() => notify("Support center is coming in the next standalone-site update.")}><i>?</i><span>Support</span></button></div></aside><section className="workspace"><header className="topbar"><button className="mobile-menu" onClick={() => setSidebarOpen((open) => !open)}>☰</button><div className="crumb"><span /> Standalone prelaunch</div><div className="top-actions"><button className="wallet" onClick={() => go("Profile")}><span>◆</span><b>{money(balance)}</b><small>GEMS</small></button><button className="primary deposit-button" onClick={() => go("Cases")}>+ Add gems</button><button className="avatar" onClick={() => go("Profile")}>{(user?.robloxUsername || "P")[0].toUpperCase()}</button></div></header><main className="content">{notice && <div className="toast">{notice}</div>}<Page /></main></section>{loginOpen && <div className="modal-backdrop" onMouseDown={() => !busy && setLoginOpen(false)}><section className="login-modal" role="dialog" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setLoginOpen(false)}>×</button><div className="login-art"><span>✦</span><b>PETLUCK</b><h2>Make your<br />profile yours.</h2></div><div className="login-form"><p className="eyebrow">ROBLOX VERIFICATION</p><h2>{loginStep === "start" ? "Start verification" : "Your private phrase"}</h2>{loginStep === "start" ? <form onSubmit={beginRoblox}><p>Enter a Roblox username. We’ll create a short unique phrase that you can place in your profile About section.</p><label>Roblox username<input value={robloxUsername} onChange={(event) => setRobloxUsername(event.target.value)} placeholder="YourRobloxUsername" required autoFocus /></label><button className="primary full" disabled={busy}>{busy ? "Checking..." : "Get verification phrase"}</button></form> : <div><p>Add this phrase to your Roblox profile’s <b>About</b> field, save, then verify.</p><code>{phrase}</code><button className="primary full" onClick={verifyRoblox} disabled={busy}>{busy ? "Checking..." : "Verify now"}</button><button className="text-button center" onClick={() => setLoginStep("start")}>Use a different username</button></div>}</div></section></div>}</div>;
}

function Stat({ icon, label, value, text }) { return <article className="stat"><span>{icon}</span><div><small>{label}</small><b>{value}</b><p>{text}</p></div></article>; }
function SectionTitle({ eyebrow, title, action, onClick }) { return <div className="section-title"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><button className="text-button" onClick={onClick}>{action} →</button></div>; }
function BetInput({ value, setValue, balance }) { return <label className="field-label">Bet amount<div className="bet-input"><input type="number" min="10" value={value} onChange={(event) => setValue(Number(event.target.value))} /><button onClick={() => setValue(Math.max(10, Math.floor(value / 2)))}>½</button><button onClick={() => setValue(Math.min(balance, value * 2))}>2×</button><button onClick={() => setValue(balance)}>Max</button></div><small>Available: {money(balance)} gems</small></label>; }
function EmptyCards({ count }) { return <div className="cards">{Array.from({ length: count }, (_, index) => <div className="card-empty" key={index} />)}</div>; }
function Empty({ text }) { return <div className="empty"><span>✦</span><p>{text}</p></div>; }
function History({ rows }) { return <div className="history-list">{rows.map((item, index) => <div key={`${item.game}-${item.at}-${index}`}><span>{item.game}</span><b>{item.result}</b><small>{item.at}</small><strong className={item.payout ? "positive" : "muted"}>{item.payout ? `+${money(item.payout)}` : `-${money(item.amount)}`}</strong></div>)}</div>; }
